### ISSUE TITLE
Make it compatible with an array of feeds

### ISSUE THREAD

**Issue by miduga** [fent/node-feedsub#13]
Could be possible to make it compatible with an array of feeds instead only by passing a single URL?

**Comment by fent** [comment]
Couldn't you create multiple instances for this?

**Comment by miduga** [comment]
Indeed. But, I was thinking, if it would have more sense to allow directly to put an array as creating new instances and getting events for all of them could cause more confusion.

**Comment by fent** [comment]
I don't think it's that confusing. If you only want to monitor from one source, you can create a parent event emitter and route the events from the feedsub instances to there.

**Comment by miduga** [comment]
Ok! Still not convinced about doing it that way, but I understand your point.

**Comment by fent** [comment]
Maybe this could help?

https://github.com/fent/node-eventyoshi
