### ISSUE TITLE
How to prevent feedsub getting items on start

### ISSUE THREAD

**Issue by thulank** [fent/node-feedsub#14]
I'm trying any options provided but, i quite confused, when starting it takes 50 items. unless i set the interval to zero (that's like a real time?). where i do wrong? i just want to set feedsub to listening on start and do callback when items comes. 

btw it's great npm packages, love this, keep up the good work :)

**Comment by thulank** [comment]
i found this, it only happen to some url like [this one](http://techno.okezone.com/feed) but no big deal :)

**Comment by fent** [comment]
There is the `emitOnStart` option

https://github.com/fent/node-feedsub#new-feedsubfeed-options
