### ISSUE TITLE
skipHours and skipDate cant work

### ISSUE THREAD

**Issue by StarpTech** [fent/node-feedsub#19]
See https://github.com/fent/node-feedsub/blob/master/lib/feedsub.js#L240 `skipHours` and `skipDate` are always undefined. I think you forgot to compare it with the `lastDate`

**Comment by fent** [comment]
I think you linked to the wrong line? I don't see `skipHours` or `skipDays` there. And if you meant that the problem is they're not referenced there, it's because `options.hours` and `options.days` are set when those options are set.

Probably shouldn't be set on `options` though.

**Comment by StarpTech** [comment]
Hi @fent I set `skipHours = true` but it never works because options.hours is undefined.

**Comment by StarpTech** [comment]
Ok I understand it is possible to skip specific hours and you can control it with `skipHours` I couldn't find this in the docs. (after some rummage I could find it in the comments :D) thanks

**Comment by fent** [comment]
Ah, `skipHours` without `hours` is supposed to look at the feed's specified hours. Same for days. It could be that the feed does not have those tags.

But, I'll add `hours` and `days` to the docs. And they should probably be changed to `hoursToSkip` and `daysToSkip` to be more specific.
