### ISSUE TITLE
Support paged feeds

### ISSUE THREAD

**Issue by StarpTech** [fent/node-feedsub#20]
Hi, it is common that a feed can support paging by defining a `next` link. It would be very efficient if we could take advantage of that. 

https://tools.ietf.org/html/rfc5005#section-3

**Comment by fent** [comment]
This module is meant to be used as subscriber-like, with interest mostly on new items as they get published.

**Comment by StarpTech** [comment]
yes I understand but it would be very efficient to process a small page of feeds instead to iterate over thousand of items even when they are already outdated. This is the job of the subscriber because its part of the protocol.

**Comment by fent** [comment]
In case of a paged feed, it will only look at the first page. And it will already not process further items and abort the download if it encounters one it has before.
