### ISSUE TITLE
Old feed items delivered by item emitter?

### ISSUE THREAD

**Issue by pro-sumer** [fent/node-feedsub#52]
When using this feed (to track software updates):

http://tweakers.net/feeds/meuktracker.xml

`node-feedsub`'s item emitter seems to emit all published items, instead of only new ones.

What am I doing wrong?

```
const FeedSub = require('feedsub')
const reader = new FeedSub('http://tweakers.net/feeds/meuktracker.xml', { interval: 1 })
reader.on('item', item => {
    console.log(item.title)
})
reader.start()
```

(The feed does seem to have a correct `pubDate` field and the individual items as well)

**Comment by atwellpub** [comment]
@pro-sumer I ran into this yesterday and I increased maxHistory to 50 and the problem went away.

**Comment by pro-sumer** [comment]
@atwellpub Thanks! I will experiment with a higher `maxHistory` value (and will post the result here).

**Comment by pro-sumer** [comment]
Seemed to help for a couple of hours, but then I ran into #53.

**Comment by fent** [comment]
so this was happening because, usually rss feeds are ordered by placing newer items at the start, and older items at the end. the above feed was sorting items from old to new (not anymore).

fix has been deployed to support both types of feeds. try out the new release.
