### ISSUE TITLE
Emitted 'error' event on Gunzip instance

### ISSUE THREAD

**Issue by eaconner** [fent/node-feedsub#57]
After upgrading to v0.7.4 I started periodically receiving the following error message.

```
events.js:288
      throw er; // Unhandled 'error' event
      ^

Error: unexpected end of file
    at Zlib.zlibOnError [as onerror] (zlib.js:180:17)
Emitted 'error' event on Gunzip instance at:
    at errorOrDestroy (internal/streams/destroy.js:108:12)
    at Gunzip.onerror (_stream_readable.js:746:7)
    at Gunzip.emit (events.js:311:20)
    at Zlib.zlibOnError [as onerror] (zlib.js:183:8) {
  errno: -5,
  code: 'Z_BUF_ERROR'
}
```

**Comment by fent** [comment]
could you share the feed where this is happening? i've tried two random rss feeds with gzip encoding, but so far unable to reproduce

**Comment by eaconner** [comment]
I have a list of 88 YouTube channel feeds and I'm unable to determine which one or ones are causing the issue. Here is an example feed: [https://www.youtube.com/feeds/videos.xml?channel_id=UCcXhhVwCT6_WqjkEniejRJQ](https://www.youtube.com/feeds/videos.xml?channel_id=UCcXhhVwCT6_WqjkEniejRJQ)

**Comment by fent** [comment]
any options passed to feedsub? been trying to reproduce this

**Comment by eaconner** [comment]
```
let reader = new feedSub(feed, {
    interval: 10,
    autoStart: true,
    maxHistory: 15,
    emitOnStart: true
});
```

**Comment by eaconner** [comment]
I think this might be a bug with Node v12. I switched from v12.16.1 to v14.15.1 and it hasn't crashed yet.

**Comment by fent** [comment]
it's a bug with my code, specifically [miniget](https://github.com/fent/node-miniget). i've tracked it down but still testing some things
