### ISSUE TITLE
tiny-typed-emitter should be (production) dependencies

### ISSUE THREAD

**Issue by jesec** [fent/node-feedsub#59]
Otherwise TS projects that depends on feedsub need to add `tiny-typed-emitter` to their devDependencies. That messes up the dependency chain. 

Additionally, `FeedItem` type should be (re)exported via `export {FeedItem} from 'feedme';`.

**Comment by fent** [comment]
hi, thanks for the feedback. this change was just pushed, i wasn't sure about putting `tiny-typed-emitter` in either `dependencies` or `devDependencies`. but now i see that compiled code in `dist/feedsub.js` does reference it. i don't know why i didn't think to check, so thanks for letting me know.
