### ISSUE TITLE
Error: aborted

### ISSUE THREAD

**Issue by jesec** [fent/node-feedsub#60]
Recently my program crashes when I use feedsub. 

```
node:events:353
      throw er; // Unhandled 'error' event

Error: aborted
    at connResetException (node:internal/errors:631:14)
    at TLSSocket.socketCloseListener (node:_http_client:434:19)
    at TLSSocket.emit (node:events:388:22)
    at node:net:666:12
    at TCP.done (node:_tls_wrap:573:7)
```

The issue seems to be related to miniget. I guess there is an unhandled exception. From Node.js 15, unhandled promises lead to a full program crash.

```
...
request (https:326)
doDownload (\home\download\flood\node_modules\miniget\dist\index.js:170)
processTicksAndRejections (internal/process/task_queues:75)
...
```

dep graph:
```
├─┬ feedsub@0.7.6
│ ├─┬ feedme@2.0.2
│ │ ├── clarinet@0.12.4
│ │ └── sax@1.2.4 deduped
│ ├── miniget@4.1.0
│ ├── newsemitter@1.0.2
│ └── tiny-typed-emitter@2.0.3
```

**Comment by fent** [comment]
hmm, how did this happen? any way to reproduce?

**Comment by jesec** [comment]
No special step needed to reproduce. Simply run and wait for a few minutes.  Though, in order to make the "error" case happen, I assume you would have to pick a RSS site which has unstable connection or has rate limits.

**Comment by fent** [comment]
do you have a url i can try?

**Comment by jesec** [comment]
> do you have a url i can try?

I just reproduced the issue with NYTimes RSS feed: 

https://rss.nytimes.com/services/xml/rss/nyt/HomePage.xml

**Comment by fent** [comment]
ah, i'm able to reproduce. but only on node v15. will have to investigate what's going on underneath. i know that recent major node versions have had substantial changes to the way streams work, including how they are destroyed/aborted
